ALTER TABLE "PrintTemplate" ADD COLUMN "cutMarkMode" TEXT NOT NULL DEFAULT 'CORNER_MARKS';
ALTER TABLE "PrintTemplate" ADD COLUMN "cutMarkLengthMm" DECIMAL NOT NULL DEFAULT 8;
ALTER TABLE "PrintTemplate" ADD COLUMN "cutMarkOffsetMm" DECIMAL NOT NULL DEFAULT 3;
ALTER TABLE "PrintTemplate" ADD COLUMN "cutMarkThicknessMm" DECIMAL NOT NULL DEFAULT 0.3;

ALTER TABLE "PrintSheet" ADD COLUMN "cutMarkMode" TEXT NOT NULL DEFAULT 'FULL_OUTLINE';
ALTER TABLE "PrintSheet" ADD COLUMN "cutMarkLengthMm" DECIMAL NOT NULL DEFAULT 8;
ALTER TABLE "PrintSheet" ADD COLUMN "cutMarkOffsetMm" DECIMAL NOT NULL DEFAULT 3;
ALTER TABLE "PrintSheet" ADD COLUMN "cutMarkThicknessMm" DECIMAL NOT NULL DEFAULT 0.3;
